language: php

php:
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer config --list --global
  - ./sandbox_setup.sh
  
script: cd sandbox;phpunit

after_script:
  - ./sandbox_destroy.sh
